FROM node:14.0-alpine3.11

WORKDIR /usr/app

COPY package.json .

# 设置时区为上海
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

RUN apk --no-cache add autoconf automake build-base libtool nasm bash lcms2-dev libpng-dev && \
  npm install --production --quiet
