export const OAUTH_APPLICATION_STRATEGY_CONFIG = Symbol('OAUTH_APPLICATION_STRATEGY_CONFIG');

export const JWT_SECRET_CONFIG = Symbol('JWT_SECRET_CONFIG');

export const REDIS_CONFIG = Symbol('REDIS_CONFIG');
