// comment https://developer.github.com/webhooks/event-payloads/#webhook-payload-object-common-properties
export enum EventType {
  ping = 'ping',
  check_run = 'check_run',
  check_suite = 'check_suite',
  commit_comment = 'commit_comment',
  content_reference = 'content_reference',
  create = 'create',
  delete = 'delete',
  deploy_key = 'deploy_key',
  deployment = 'deployment',
  deployment_status = 'deployment_status',
  fork = 'fork',
  github_app_authorization = 'github_app_authorization',
  gollum = 'gollum',
  installation = 'installation',
  installation_repositories = 'installation_repositories',
  issue_comment = 'issue_comment',
  issues = 'issues',
  label = 'label',
  marketplace_purchase = 'marketplace_purchase',
  member = 'member',
  membership = 'membership',
  meta = 'meta',
  milestone = 'milestone',
  organization = 'organization',
  org_block = 'org_block',
  package = 'package',
  page_build = 'page_build',
  project_card = 'project_card',
  project_column = 'project_column',
  project = 'project',
  public = 'public',
  pull_request = 'pull_request',
  pull_request_review = 'pull_request_review',
  pull_request_review_comment = 'pull_request_review_comment',
  push = 'push',
  release = 'release',
  repository_dispatch = 'repository_dispatch',
  repository = 'repository',
  repository_import = 'repository_import',
  repository_vulnerability_alert = 'repository_vulnerability_alert',
  security_advisory = 'security_advisory',
  sponsorship = 'sponsorship',
  star = 'star',
  status = 'status',
  team = 'team',
  team_add = 'team_add',
  watch = 'watch',
}

export enum MsgType {
  text = 'text',
  markdown = 'markdown',
}

export interface ActionType<T extends { action: unknown }> {
  action: T['action'];
}
