name: app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        docker-repository: [powerfulyang/api.powerfulyang.com]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          npm ci
          npm run build
      - name: Dockerize
        id: dockerize
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ matrix.docker-repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest'
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: false
          script: |
            docker pull ${{ matrix.docker-repository }}
            cd ~/applications
            docker-compose up -d --force-recreate api.powerfulyang.com
