name: qa

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-repository: [powerfulyang/qa.api.powerfulyang.com]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerize
        id: dockerize
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ matrix.docker-repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: false
          script: |
            docker pull ${{ matrix.docker-repository }}
            cd ~/applications/qa
            docker-compose up -d --force-recreate qa.api.powerfulyang.com
            docker image prune -a -f
